# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X2-gXMX2QsjNlud-wH0uLLQhbTW6bR1B
"""

import numpy as np
import matplotlib.pyplot as plt
i=np.array([[[255,255,0]]])
plt.imshow(i)